### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by yarqian** [guanyingc/DeepHDRVideo#8]
Hi, many thanks for your work and codes. I tested the pretrained model on GPU and it works. But I tried to retrained the model but I got cudnn error like"
  File "main.py", line 33, in <module>
    main(args)
  File "main.py", line 21, in main
    train_utils.train(args, log, train_loader, model, epoch, recorder)
  File "/media/ye/ssd11/DeepHDRVideo-master/utils/train_utils.py", line 17, in train
    pred = model.forward(split='train'); 
  File "/media/ye/ssd11/DeepHDRVideo-master/models/hdr2E_flow_model.py", line 93, in forward
    self.fpred = self.fnet(fnet_in)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ye/ssd11/DeepHDRVideo-master/models/archs/flow_networks.py", line 94, in forward
    flow1, flow2 = self.moduleBasic[i](input)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ye/ssd11/DeepHDRVideo-master/models/archs/flow_networks.py", line 33, in forward
    flows = self.moduleBasic(inputs).clamp(-320, 320)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ye/.opt/miniconda/envs/torch11/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
"
And I checked the codes and there is no setting for cudnn. So could you help me for this problem? Many thansk.

**Comment by guanyingc** [comment]
Hi, could you let me know the versions of python/pytorch/cuda/cudnn in your environment?

**Comment by yarqian** [comment]
Many thanks. I have fixed it. The problem came from the virtual environment in conda since there is no cudnn version 7.5.1 in conda. When i install it in local, the problem is solved.
